
const fakeData = [{"id":1,"first_name":"Tab","last_name":"Sancroft","email":"tsancroft0@house.gov","phone": "01516144693","gender":"Agender","annual_salary":7558,"photo": "https:\/\/images-na.ssl-images-amazon.com\/images\/M\/MV5BNjk1MjIxNjUxNF5BMl5BanBnXkFtZTcwODk2NzM4Mg@@._V1_UY256_CR3,0,172,256_AL_.jpg"},
{"id":2,"first_name":"Danny","last_name":"Savage","email":"dsavage1@alibaba.com","phone": "01516864693","gender":"Genderfluid","annual_salary":4654,"photo": "https:\/\/uifaces.co\/our-content\/donated\/hh33bQqB.jpg"},
{"id":3,"first_name":"Obediah","last_name":"Pulfer","email":"opulfer2@rediff.com","phone": "01516144093","gender":"Female","annual_salary":2537,"photo": "https:\/\/images.generated.photos\/paAqjtzf1YcKLboO6vuKNAM-KlPDsZGu5K4IeT7eX78\/rs:fit:512:512\/Z3M6Ly9nZW5lcmF0\/ZWQtcGhvdG9zLzA5\/OTUzNzkuanBn.jpg"},
{"id":4,"first_name":"Andriette","last_name":"Pitkaithly","email":"apitkaithly3@fotki.com","phone": "01556144693","gender":"Genderfluid","annual_salary":5238,"photo": "https:\/\/images.generated.photos\/8aT4WFrZGNATmlJ_BNyyfn8iC6ZjQwy4hFDB9qmg7yo\/rs:fit:512:512\/Z3M6Ly9nZW5lcmF0\/ZWQtcGhvdG9zLzA5\/OTgxNTkuanBn.jpg"},
{"id":5,"first_name":"Clair","last_name":"Whitney","email":"cwhitney4@livejournal.com","phone": "02316144693","gender":"Male","annual_salary":3013,"photo": "https:\/\/uifaces.co\/our-content\/donated\/rHpGHoRb.jpeg","photo": "https:\/\/i.imgur.com\/xqgjKVq.jpg"},
{"id":6,"first_name":"Baily","last_name":"Klos","email":"bklos5@51.la","phone": "01516144601","gender":"Bigender","annual_salary":2877,"photo": "https:\/\/uifaces.co\/our-content\/donated\/oT06seM-.png","photo": "https:\/\/uifaces.co\/our-content\/donated\/XPz-t8Wr.jpg"},
{"id":7,"first_name":"Rozanna","last_name":"Georghiou","email":"rgeorghiou6@istockphoto.com","phone": "01513214693","gender":"Female","annual_salary":7575,"photo": "https:\/\/images-na.ssl-images-amazon.com\/images\/M\/MV5BNjY0NDE5MDQ5OF5BMl5BanBnXkFtZTcwMTI4MDQxOA@@._V1_UY256_CR12,0,172,256_AL_.jpg"},
{"id":8,"first_name":"Lauri","last_name":"Eatttok","email":"leatttok7@illinois.edu","phone": "01516112393","gender":"Agender","annual_salary":8128,"photo": "https:\/\/randomuser.me\/api\/portraits\/women\/13.jpg"},
{"id":9,"first_name":"Lonna","last_name":"Giraudel","email":"lgiraudel8@fastcompany.com","phone": "01123444693","gender":"Polygender","annual_salary":6536,"photo": "https:\/\/randomuser.me\/api\/portraits\/men\/53.jpg"},
{"id":10,"first_name":"Candi","last_name":"Dowthwaite","email":"cdowthwaite9@nbcnews.com","phone": "01876144693","gender":"Polygender","annual_salary":5511,"photo": "https:\/\/randomuser.me\/api\/portraits\/men\/10.jpg"},
{"id":11,"first_name":"Romonda","last_name":"MacCahey","email":"rmaccaheya@jugem.jp","phone": "01516145693","gender":"Genderqueer","annual_salary":5710,"photo": "https:\/\/randomuser.me\/api\/portraits\/women\/27.jpg"},
{"id":12,"first_name":"Korney","last_name":"McCrackan","email":"kmccrackanb@canalblog.com","phone": "12346144693","gender":"Bigender","annual_salary":3128,"photo": "https:\/\/randomuser.me\/api\/portraits\/men\/97.jpg"},
{"id":13,"first_name":"Harlen","last_name":"Clemoes","email":"hclemoesc@etsy.com","phone": "01567894693","gender":"Polygender","annual_salary":6417,"photo": "https:\/\/uifaces.co\/our-content\/donated\/oLkb60i_.jpg"},
{"id":14,"first_name":"Hort","last_name":"Janic","email":"hjanicd@friendfeed.com","phone": "01516141234","gender":"Female","annual_salary":5630,"photo": "https:\/\/uifaces.co\/our-content\/donated\/u4HmMtIQ.jpg"},
{"id":15,"first_name":"Harley","last_name":"Lathaye","email":"hlathayee@amazon.co.uk","phone": "01436144693","gender":"Male","annual_salary":9765,"photo": "https:\/\/images-na.ssl-images-amazon.com\/images\/M\/MV5BMTA2MjYyNjk3MjVeQTJeQWpwZ15BbWU3MDIxOTkwNjI@._V1_UX172_CR0,0,172,256_AL_.jpg"}]

export default fakeData;